name: HAT-S_SRx4_face_finetune
model_type: HATModel
scale: 4
num_gpu: 1
manual_seed: 0

network_g:
  type: HAT
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 24
  squeeze_factor: 24
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.0
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 144
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: pixelshuffle
  resi_connection: 1conv

datasets:
  train:
    name: FFHQ_face_train
    type: PairedImageDataset
    dataroot_gt: /home/hermes/hat-face-training/data/ffhq_face_sr/train/gt
    dataroot_lq: /home/hermes/hat-face-training/data/ffhq_face_sr/train/lq
    io_backend:
      type: disk
    gt_size: 256
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: FFHQ_face_val
    type: PairedImageDataset
    dataroot_gt: /home/hermes/hat-face-training/data/ffhq_face_sr/val/gt
    dataroot_lq: /home/hermes/hat-face-training/data/ffhq_face_sr/val/lq
    io_backend:
      type: disk

path:
  pretrain_network_g: experiments/pretrained_models/HAT-S_SRx4.pth
  strict_load_g: true

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.99]
  scheduler:
    type: MultiStepLR
    milestones: [25000, 40000, 45000, 47500]
    gamma: 0.5
  total_iter: 250000
  warmup_iter: -1
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: !!float 5e3
  save_img: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true

dist_params:
  backend: gloo
  port: 29500
